### ISSUE TITLE
module 'jittor' has no attribute 'triu_'

### ISSUE THREAD

**Issue by XD-mu** [uyzhang/JCLIP#1]
在运行demo.py的时候报错：
Traceback (most recent call last):
  File "demo.py", line 7, in <module>
    model, preprocess = clip.load("ViT-B-32.pkl")
  File "/data1/mcy/code/DailyProject/jittor-race-few-shot/baseline/JCLIP-main/jclip/clip.py", line 159, in load
    model = build_model(state_dict)
  File "/data1/mcy/code/DailyProject/jittor-race-few-shot/baseline/JCLIP-main/jclip/model.py", line 279, in build_model
    transformer_width, transformer_heads, transformer_layers)
  File "/data1/mcy/code/DailyProject/jittor-race-few-shot/baseline/JCLIP-main/jclip/model.py", line 160, in __init__
    attn_mask=self.build_attention_mask())
  File "/data1/mcy/code/DailyProject/jittor-race-few-shot/baseline/JCLIP-main/jclip/model.py", line 193, in build_attention_mask
    mask = jt.triu_(mask, 1)  # zero out the lower diagonal
AttributeError: module 'jittor' has no attribute 'triu_'
之前jittor框架搭建里面的所有都正常运行

**Comment by uyzhang** [comment]
将计图版本到最新，再试试。

**Comment by XD-mu** [comment]
找到问题了，是你们编写代码出问题了，我将triu_改成triu就好了

**Comment by XD-mu** [comment]
我的计图已经最新了
